version: '3.8'

services:
  backend:
    build: 
      context: ./CityScoutBACK
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/cityscout
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=yourpassword
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - db
    networks:
      - cityscout-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=cityscout
      - MYSQL_ROOT_PASSWORD=yourpassword
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - cityscout-network

volumes:
  mysql_data:

networks:
  cityscout-network:
    driver: bridge
